name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.7
        uses: actions/setup-node@v3
        with:
          node-version: 18.7
      - run: npm ci
      - run: npm test
