name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.7
        uses: actions/setup-node@v3
        with:
          node-version: 18.7
      - run: npm ci
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1/4, 2/4, 3/4, 4/4]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.7
        uses: actions/setup-node@v3
        with:
          node-version: 18.7
      - run: npm ci
      - run: npx vitest run --shard=${{ matrix.shard }}
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.7
        uses: actions/setup-node@v3
        with:
          node-version: 18.7
      - run: npm ci
      - run: npm run bench
